#!/usr/bin/env bash
# Tansfering a file from a client to a server
if [ "$#" -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Assign variables based on arguments
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Use scp to transfer the file to the user's home directory on the remote server
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

# Check if scp command succeeded
if [ "$?" -eq 0 ]; then
  echo "File transfer successful."
else
  echo "File transfer failed."
fi
